"""
reporting/h1_formatter.py — Format a finding into HackerOne markdown report template.

No network. No LLM. Pure formatting.
"""
from __future__ import annotations
from datetime import datetime


def format_h1_report(
    title:           str,
    severity:        str,
    cvss_score:      float,
    cvss_vector:     str,
    steps:           str,
    impact:          str,
    supporting:      str = "",
    remediation:     str = "",
    program:         str = "",
    host:            str = "",
    template_id:     str = "",
) -> str:
    """
    Format a finding as a HackerOne-ready markdown report.

    Returns a markdown string. NEVER submits — operator reviews and submits manually.
    """
    now = datetime.now().strftime("%Y-%m-%d")
    header_lines = [f"# {title}", ""]

    if program:
        header_lines.append(f"**Program:** {program}  ")
    if host:
        header_lines.append(f"**Host:** `{host}`  ")
    header_lines.append(f"**Date:** {now}  ")
    header_lines.append(f"**CVSS 3.1:** {cvss_score} ({severity}) — `{cvss_vector}`  ")
    if template_id:
        header_lines.append(f"**Template:** `{template_id}`  ")
    header_lines.append("")
    header_lines.append("---")
    header_lines.append("")

    sections = [
        "## Summary",
        f"{title}. This vulnerability was identified during authorized security testing.",
        "",
        "## Severity",
        f"**{severity}** (CVSS 3.1: {cvss_score})",
        f"Vector: `{cvss_vector}`",
        "",
        "## Steps to Reproduce",
        steps or "_Steps to reproduce to be documented by operator._",
        "",
        "## Supporting Material / Evidence",
        supporting or "_Screenshots and network captures to be attached by operator._",
        "",
        "## Impact",
        impact or "_Impact assessment to be completed by operator._",
        "",
    ]
    if remediation:
        sections += [
            "## Remediation Suggestion",
            remediation,
            "",
        ]

    sections += [
        "---",
        "> DRAFT — Operator review required before submission.",
        "> This report was generated by JARVIS and has NOT been submitted.",
        "> Review all details, add evidence, and submit manually via HackerOne.",
    ]

    return "\n".join(header_lines + sections)
